export const refs = {
	body: document.querySelector('body'),
	filmsContainer: document.querySelector('.js-films-container'),
	filmsUl: document.querySelector('.films'),
	filmsItem: document.querySelector('.films__item'),
	modal: document.querySelector('[data-modal]'),
	boxTeam: document.querySelector('#box-team'),
	footerLink: document.querySelector('.footer__link'),
	modalClose: document.querySelector('[data-modal-close]'),
	modalWrapper: document.querySelector('.modal--wrapper'),
	paginator: document.querySelector('#pagination'),
	btnWatched: document.querySelector('.btn-watched'),
	btnQueue: document.querySelector('.btn-queue'),
	paginatorBox: document.querySelector('#section-paginator'),
};
